CREATE TABLE users(
    user_id BIGINT NOT NULL AUTO_INCREMENT, 
    address VARCHAR(255), 
    birth_day DATE, 
    gender VARCHAR(255), 
    user_name VARCHAR(255) NOT NULL, 
    create_at DATETIME(6), 
    update_at DATETIME(6), 
    PRIMARY KEY (user_id)
);

CREATE TABLE roles(
    role_id BIGINT NOT NULL AUTO_INCREMENT,
    role_name VARCHAR(255) NOT NULL,
    role_description VARCHAR(255),
    create_at DATETIME(6), 
    update_at DATETIME(6), 
    PRIMARY KEY (role_id)
);

CREATE TABLE accounts(
    acc_id BIGINT NOT NULL AUTO_INCREMENT,
    role_id BIGINT NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    hash_pass VARCHAR(255) NOT NULL,
    create_at DATETIME(6),
    update_at DATETIME(6),
    user_id BIGINT NOT NULL,
    PRIMARY KEY (acc_id),
    FOREIGN KEY (role_id) REFERENCES roles(role_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE permission(
    per_id BIGINT NOT NULL AUTO_INCREMENT,
    per_module VARCHAR(255) NOT NULL,
    per_name VARCHAR(255) NOT NULL,
    create_at DATETIME(6), 
    update_at DATETIME(6), 
    PRIMARY KEY (per_id)
);

CREATE TABLE roles_permissions(
    role_id BIGINT NOT NULL,
    per_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, per_id)
);

CREATE TABLE mobile(
    mob_id BIGINT NOT NULL AUTO_INCREMENT,
    mob_name VARCHAR(255) NOT NULL,
    mob_model VARCHAR(255) NOT NULL,
    mob_type VARCHAR(255) NOT NULL,
    mob_quant INT NOT NULL,
    mob_price VARCHAR(255) NOT NULL,
    mob_desc VARCHAR(255),
    create_at DATETIME(6), 
    update_at DATETIME(6), 
    PRIMARY KEY (mob_id)
);

CREATE TABLE customers(
    cus_id BIGINT NOT NULL AUTO_INCREMENT,
    cus_name VARCHAR(255) NOT NULL,
    cus_email VARCHAR(255),
    cus_address VARCHAR(255),
    cus_gender VARCHAR(255),
    cus_birth_day DATE,
    create_at DATETIME(6),
    update_at DATETIME(6),
    PRIMARY KEY (cus_id)
);

CREATE TABLE payment(
    pay_id BIGINT NOT NULL AUTO_INCREMENT,
    pay_desc VARCHAR(255),
    pay_method VARCHAR(255) NOT NULL,
    create_at DATETIME(6), 
    update_at DATETIME(6), 
    PRIMARY KEY (pay_id)
);

CREATE TABLE customer_payment(
    pay_id BIGINT NOT NULL,
    cus_id BIGINT NOT NULL,
    PRIMARY KEY (pay_id, cus_id)
);

CREATE TABLE transactions(
    trans_id BIGINT NOT NULL AUTO_INCREMENT,
    trans_name VARCHAR(255) NOT NULL,
    trans_type VARCHAR(255) NOT NULL,
    pay_id BIGINT NOT NULL,
    create_at DATETIME(6), 
    update_at DATETIME(6), 
    PRIMARY KEY (trans_id),
    FOREIGN KEY (pay_id) REFERENCES payment(pay_id)
);



INSERT INTO mobile(mob_name, mob_model, mob_type, mob_quant, mob_price, mob_desc, create_at, update_at) VALUES
("iPhone 15", "Apple","iPhone", 21, "15,000,000 VND" , "Sample Desc", NOW(), NOW()),
("iPhone 14", "Apple","iPhone", 50, "13,000,000 VND" , "Sample Desc", NOW(), NOW()),
("iPhone 13", "Apple","iPhone", 100, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Samsung Galaxy Note 10", "Samsung","Samsung", 22, "7,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Oppo A37", "Oppo","Oppo" , 12, "11,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Xiaomi Redmi Note 8", "Xiaomi","Xiaomi", 21, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Samsung Galaxy S20", "Samsung","Samsung", 30, "20,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Google Pixel 6", "Google","Google", 40, "12,000,000 VND" , "Sample Desc", NOW(), NOW()),
("OnePlus 9 Pro", "OnePlus","OnePlus" ,10, "13,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Huawei P40", "Huawei","Huawei", 20, "14,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Sony Xperia 5 III", "Sony","Sony", 18, "16,000,000 VND",  "Sample Desc", NOW(), NOW()),
("LG Velvet", "LG","LG", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Nokia 9 PureView", "Nokia","Nokia", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Motorola Moto G Power", "Motorola","Motorola", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("ASUS ROG Phone 5", "ASUS","ASUS", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("BlackBerry Key2", "BlackBerry","BlackBerry", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Lenovo Legion Phone Duel 2", "Lenovo","Lenovo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Vivo X60 Pro", "Vivo","Vivo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Realme GT", "Realme","Realme", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Xiaomi Mi 11 Ultra", "Xiaomi","Xiaomi", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("OnePlus Nord", "OnePlus","OnePlus", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Samsung Galaxy Z Fold 3", "Samsung","Samsung", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("iPhone 12", "Apple","iPhone", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Google Pixel 5a", "Google","Google", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Sony Xperia 1 III", "Sony","Sony", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Motorola Moto G Stylus", "Motorola","Motorola", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Huawei Mate 40 Pro", "Huawei","Huawei", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("LG Wing", "LG","LG", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Nokia 8.3 5G", "Nokia","Nokia", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("ASUS Zenfone 8", "ASUS","ASUS", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("BlackBerry Evolve", "BlackBerry","BlackBerry", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Lenovo Legion Phone Duel", "Lenovo","Lenovo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Vivo X50 Pro", "Vivo","Vivo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Realme X7 Pro", "Realme","Realme", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Xiaomi Mi 10T Pro", "Xiaomi","Xiaomi", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("OnePlus 8T", "OnePlus","OnePlus" ,212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Samsung Galaxy Note 20 Ultra", "Samsung","Samsung", 212, "10,000,000 VND"  ,"Sample Desc", NOW(), NOW()),
("iPhone 11", "Apple","iPhone", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Google Pixel 4a", "Google","Google", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Sony Xperia 5 II", "Sony","Sony", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Motorola Moto G9 Plus", "Motorola","Motorola", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Huawei P30 Pro", "Huawei","Huawei", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("LG V60 ThinQ", "LG","LG", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Nokia 7.2", "Nokia","Nokia", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("ASUS ROG Phone 3", "ASUS","ASUS", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("BlackBerry Keyone", "BlackBerry","BlackBerry", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Lenovo Legion Phone Pro", "Lenovo","Lenovo", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Vivo V21", "Vivo","Vivo", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Realme Narzo 30 Pro", "Realme","Realme", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Xiaomi Redmi Note 9 Pro", "Xiaomi","Xiaomi", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("OnePlus 8 Pro", "OnePlus","OnePlus", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Samsung Galaxy S21 Ultra", "Samsung","Samsung", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("iPhone SE (2020)", "Apple","iPhone", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Google Pixel 5", "Google","Google", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Sony Xperia 10 II", "Sony","Sony", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Motorola Moto G Power (2021)", "Motorola","Motorola", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Huawei Mate X2", "Huawei","Huawei", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("LG G8 ThinQ", "LG","LG", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Nokia 5.3", "Nokia","Nokia", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("ASUS Zenfone 7 Pro", "ASUS","ASUS", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("BlackBerry Motion", "BlackBerry","BlackBerry", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Lenovo Legion Phone", "Lenovo","Lenovo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Vivo Y20", "Vivo","Vivo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Realme 8 Pro", "Realme","Realme", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Xiaomi Poco X3 NFC", "Xiaomi","Xiaomi", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("OnePlus Nord N10", "OnePlus","OnePlus", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Samsung Galaxy A52", "Samsung","Samsung" ,212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("iPhone XR", "Apple","iPhone", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Google Pixel 4", "Google","Google", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Sony Xperia 10 Plus", "Sony","Sony", 212, "10,000,000 VND" ,"Sample Desc", NOW(), NOW()),
("Motorola Moto G Fast", "Motorola","Motorola", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Huawei P40 Pro", "Huawei","Huawei", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("LG V40 ThinQ", "LG","LG", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Nokia 6.2", "Nokia","Nokia", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("ASUS Zenfone 6", "ASUS","ASUS", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("BlackBerry Priv", "BlackBerry","BlackBerry", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Lenovo Legion Phone 2 Pro", "Lenovo","Lenovo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Vivo Y15", "Vivo","Vivo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Realme 7 Pro", "Realme","Realme", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Xiaomi Redmi Note 7", "Xiaomi","Xiaomi", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("OnePlus 7T", "OnePlus","OnePlus", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Samsung Galaxy S20 FE", "Samsung","Samsung", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("iPhone X", "Apple","iPhone", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Google Pixel 3a", "Google","Google", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Sony Xperia 8", "Sony","Sony", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Motorola Moto G8 Power", "Motorola","Motorola", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Huawei Nova 7i", "Huawei","Huawei", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("LG Stylo 6", "LG","LG", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Nokia 3.4", "Nokia","Nokia", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("ASUS ROG Phone 2", "ASUS","ASUS", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("BlackBerry Aurora", "BlackBerry","BlackBerry", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Lenovo Legion Phone 2", "Lenovo","Lenovo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Vivo Y12", "Vivo","Vivo", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("Realme 6 Pro", "Realme","Realme", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Xiaomi Mi Note 10", "Xiaomi","Xiaomi", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW()),
("OnePlus 7 Pro", "OnePlus","OnePlus", 212, "10,000,000 VND",  "Sample Desc", NOW(), NOW()),
("Samsung Galaxy A71", "Samsung","Samsung", 212, "10,000,000 VND" , "Sample Desc", NOW(), NOW());



INSERT INTO users(address, birth_day, gender, user_name, create_at, update_at) VALUES
("District 3, Ho Chi Minh City", "1998-05-20", "Male", "trungtran1", NOW(), NOW()),
("District 5, Ho Chi Minh City", "1992-10-21", "Female", "nhuquynh2110", NOW(), NOW()),
("District 7, Ho Chi Minh City", "1999-09-11", "Male", "anhdung1109", NOW(), NOW()),
("District 10, Ho Chi Minh City", "2003-02-05", "Female", "tuyetnhi0502", NOW(), NOW()),
("District 12, Ho Chi Minh City", "2003-07-22", "Female", "trieuan123", NOW(), NOW()),
("District 1, Ho Chi Minh City", "2003-12-08", "Female", "khanhlinh11", NOW(), NOW()),
("District 2, Ho Chi Minh City", "1995-08-17", "Male", "vietanh1708", NOW(), NOW()),
("District 4, Ho Chi Minh City", "1990-03-14", "Male", "ducminh1403", NOW(), NOW()),
("District 6, Ho Chi Minh City", "1987-06-29", "Female", "thutrang296", NOW(), NOW()),
("District 8, Ho Chi Minh City", "1993-09-03", "Female", "hanhphuc0309", NOW(), NOW()),
("District 9, Ho Chi Minh City", "1985-12-12", "Male", "huyhoang1212", NOW(), NOW()),
("District 11, Ho Chi Minh City", "1997-04-26", "Male", "namson2604", NOW(), NOW()),
("Binh Tan District, Ho Chi Minh City", "1994-11-09", "Female", "ngocmai0911", NOW(), NOW()),
("Binh Thanh District, Ho Chi Minh City", "1988-02-14", "Male", "thanhcong1402", NOW(), NOW()),
("Tan Binh District, Ho Chi Minh City", "1991-07-31", "Female", "maihoa3107", NOW(), NOW()),
("Tan Phu District, Ho Chi Minh City", "1996-10-18", "Male", "dinhquan1810", NOW(), NOW()),
("Phu Nhuan District, Ho Chi Minh City", "1998-03-25", "Female", "thuytrang2503", NOW(), NOW()),
("Go Vap District, Ho Chi Minh City", "1990-06-01", "Male", "tienquan0106", NOW(), NOW()),
("Thu Duc City, Ho Chi Minh City", "1989-09-15", "Male", "vanduc1509", NOW(), NOW()),
("Can Gio District, Ho Chi Minh City", "1995-12-23", "Female", "hoangyen2312", NOW(), NOW()),
("Cu Chi District, Ho Chi Minh City", "1992-05-08", "Male", "quanminh0805", NOW(), NOW()),
("Hoc Mon District, Ho Chi Minh City", "1993-08-20", "Male", "thanhdat2008", NOW(), NOW()),
("Nha Be District, Ho Chi Minh City", "1997-01-10", "Female", "ngochuyen1001", NOW(), NOW()),
("District 13, Ho Chi Minh City", "1996-04-12", "Male", "vuongbao1204", NOW(), NOW()),
("Binh Chanh District, Ho Chi Minh City", "1986-11-04", "Female", "phuongnga0411", NOW(), NOW()),
("Cu Chi District, Ho Chi Minh City", "1991-02-28", "Male", "huynghoa2802", NOW(), NOW()),
("Hoc Mon District, Ho Chi Minh City", "1990-07-09", "Female", "ngochau0907", NOW(), NOW()),
("District 8, Ho Chi Minh City", "1993-10-15", "Male", "vantrung1510", NOW(), NOW()),
("District 12, Ho Chi Minh City", "1998-01-05", "Male", "phuongphat0501", NOW(), NOW()),
("Thu Duc City, Ho Chi Minh City", "1987-04-29", "Female", "thikim2904", NOW(), NOW()),
("District 4, Ho Chi Minh City", "1992-09-03", "Male", "minhhieu0309", NOW(), NOW()),
("District 9, Ho Chi Minh City", "1999-11-18", "Female", "thuthao1811", NOW(), NOW()),
("District 11, Ho Chi Minh City", "1996-06-26", "Male", "truongtuan2606", NOW(), NOW()),
("District 3, Ho Chi Minh City", "1985-03-14", "Male", "ducanh1403", NOW(), NOW()),
("District 1, Ho Chi Minh City", "1989-08-07", "Female", "thimai0708", NOW(), NOW()),
("District 5, Ho Chi Minh City", "1997-12-30", "Male", "trunghieu3012", NOW(), NOW()),
("Binh Tan District, Ho Chi Minh City", "1988-05-19", "Female", "tramngoc1905", NOW(), NOW()),
("Binh Thanh District, Ho Chi Minh City", "1991-10-02", "Male", "anhlinh0210", NOW(), NOW()),
("Tan Binh District, Ho Chi Minh City", "1994-03-26", "Male", "tuananh2603", NOW(), NOW()),
("Tan Phu District, Ho Chi Minh City", "1999-08-14", "Female", "linhchi1408", NOW(), NOW()),
("Phu Nhuan District, Ho Chi Minh City", "1986-11-27", "Male", "vanphuc2711", NOW(), NOW()),
("Go Vap District, Ho Chi Minh City", "1993-02-12", "Female", "ngoclan1202", NOW(), NOW()),
("Thu Duc City, Ho Chi Minh City", "1987-07-05", "Male", "thanhphong0507", NOW(), NOW()),
("Can Gio District, Ho Chi Minh City", "1990-01-24", "Female", "ngocdung2401", NOW(), NOW()),
("Cu Chi District, Ho Chi Minh City", "1995-04-17", "Male", "vietcuong1704", NOW(), NOW()),
("Hoc Mon District, Ho Chi Minh City", "1989-09-06", "Male", "thanhthien0609", NOW(), NOW()),
("Nha Be District, Ho Chi Minh City", "1992-12-01", "Female", "hongloan0112", NOW(), NOW()),
("District 13, Ho Chi Minh City", "1998-05-09", "Male", "hoainam0905", NOW(), NOW()),
("Binh Chanh District, Ho Chi Minh City", "1993-10-28", "Female", "phuongthao2810", NOW(), NOW()),
("Cu Chi District, Ho Chi Minh City", "1990-01-15", "Male", "datviet1501", NOW(), NOW()),
("Hoc Mon District, Ho Chi Minh City", "1995-08-22", "Female", "lanhuong2208", NOW(), NOW()),
("District 8, Ho Chi Minh City", "1986-03-17", "Male", "duongdat1703", NOW(), NOW()),
("District 12, Ho Chi Minh City", "1987-06-30", "Male", "tuananh3006", NOW(), NOW()),
("Thu Duc City, Ho Chi Minh City", "1992-11-16", "Female", "hongnga1611", NOW(), NOW()),
("District 4, Ho Chi Minh City", "1997-04-03", "Male", "ducminh0304", NOW(), NOW()),
("District 9, Ho Chi Minh City", "1990-07-27", "Female", "thithanh2707", NOW(), NOW()),
("District 11, Ho Chi Minh City", "1993-09-13", "Male", "tuananh1309", NOW(), NOW()),
("District 3, Ho Chi Minh City", "1996-12-08", "Male", "minhduc0812", NOW(), NOW()),
("District 1, Ho Chi Minh City", "1991-03-21", "Female", "thithao2103", NOW(), NOW()),
("District 5, Ho Chi Minh City", "1994-06-29", "Male", "huyhoang2906", NOW(), NOW()),
("Binh Tan District, Ho Chi Minh City", "1989-09-14", "Female", "thuylinh1409", NOW(), NOW()),
("Binh Thanh District, Ho Chi Minh City", "1992-12-11", "Male", "vietdung1212", NOW(), NOW()),
("Tan Binh District, Ho Chi Minh City", "1997-01-07", "Male", "hoanganh0701", NOW(), NOW()),
("Tan Phu District, Ho Chi Minh City", "1990-04-02", "Female", "thuytram0204", NOW(), NOW()),
("Phu Nhuan District, Ho Chi Minh City", "1995-07-19", "Male", "vandai1907", NOW(), NOW()),
("Go Vap District, Ho Chi Minh City", "1998-10-23", "Female", "tuyethong2310", NOW(), NOW()),
("Thu Duc City, Ho Chi Minh City", "1991-11-01", "Male", "vanquan0111", NOW(), NOW()),
("Can Gio District, Ho Chi Minh City", "1987-02-05", "Female", "thithuy0502", NOW(), NOW()),
("Cu Chi District, Ho Chi Minh City", "1999-05-18", "Male", "ductuan1805", NOW(), NOW()),
("Hoc Mon District, Ho Chi Minh City", "1996-08-09", "Male", "tuananh0908", NOW(), NOW()),
("Nha Be District, Ho Chi Minh City", "1988-12-28", "Female", "thithuy2812", NOW(), NOW()),
("District 13, Ho Chi Minh City", "1986-03-15", "Male", "vandung1503", NOW(), NOW()),
("Binh Chanh District, Ho Chi Minh City", "1990-06-20", "Female", "huonglinh2006", NOW(), NOW()),
("Cu Chi District, Ho Chi Minh City", "1993-09-03", "Male", "vanduong0309", NOW(), NOW()),
("Hoc Mon District, Ho Chi Minh City", "1997-12-17", "Female", "tuyethong1712", NOW(), NOW()),
("District 8, Ho Chi Minh City", "1985-05-29", "Male", "vanduong2905", NOW(), NOW()),
("District 12, Ho Chi Minh City", "1988-10-12", "Male", "honganh1210", NOW(), NOW()),
("Thu Duc City, Ho Chi Minh City", "1992-01-26", "Female", "thithanh2601", NOW(), NOW()),
("District 4, Ho Chi Minh City", "1995-04-09", "Male", "hoainam0904", NOW(), NOW()),
("District 9, Ho Chi Minh City", "1989-07-04", "Female", "hoanganh0407", NOW(), NOW()),
("District 11, Ho Chi Minh City", "1992-09-29", "Male", "huyhoang2909", NOW(), NOW()),
("District 3, Ho Chi Minh City", "1997-12-22", "Male", "anhquan2212", NOW(), NOW()),
("District 1, Ho Chi Minh City", "1990-05-05", "Female", "thanhthao0505", NOW(), NOW()),
("District 5, Ho Chi Minh City", "1993-08-18", "Male", "minhduc1808", NOW(), NOW()),
("Binh Tan District, Ho Chi Minh City", "1998-11-06", "Female", "tuyetmai0611", NOW(), NOW()),
("Binh Thanh District, Ho Chi Minh City", "1990-02-28", "Male", "thanhbinh2802", NOW(), NOW()),
("Tan Binh District, Ho Chi Minh City", "1995-05-12", "Male", "tuananh1205", NOW(), NOW()),
("Tan Phu District, Ho Chi Minh City", "1988-06-04", "Female", "thanhloan0406", NOW(), NOW()),
("Phu Nhuan District, Ho Chi Minh City", "1992-09-17", "Male", "tienthanh1709", NOW(), NOW()),
("Go Vap District, Ho Chi Minh City", "1997-03-30", "Female", "thihuong3003", NOW(), NOW()),
("Thu Duc City, Ho Chi Minh City", "1989-06-11", "Male", "tuananh1106", NOW(), NOW()),
("Can Gio District, Ho Chi Minh City", "1993-01-08", "Female", "thithao0801", NOW(), NOW()),
("Cu Chi District, Ho Chi Minh City", "1986-04-21", "Male", "vandat2104", NOW(), NOW()),
("Hoc Mon District, Ho Chi Minh City", "1991-07-14", "Male", "thanhtam1407", NOW(), NOW()),
("Nha Be District, Ho Chi Minh City", "1995-10-19", "Female", "thutrang1910", NOW(), NOW()),
("District 13, Ho Chi Minh City", "1988-03-07", "Male", "tuananh0703", NOW(), NOW()),
("Binh Chanh District, Ho Chi Minh City", "1991-06-02", "Female", "thithanh0206", NOW(), NOW());




INSERT INTO customers(cus_name, cus_email, cus_address, cus_gender, cus_birth_day, create_at, update_at) VALUES 
("DungCho","DungCho@gmail.com", "District 7, Ho Chi Minh City", "Male", "2001-09-11", NOW(), NOW()),
("TrungTran","TrungTran@gmail.com", "District 6, Ho Chi Minh City", "Male", "2003-06-20", NOW(), NOW()),
("AnhDat","AnhDat@gmail.com", "District 5, Ho Chi Minh City", "Male", "2002-05-11", NOW(), NOW()),
("HuyHoang","HuyHoang@gmail.com", "District 4, Ho Chi Minh City", "Male", "2003-04-12", NOW(), NOW()),
("DucChung","DucChung@gmail.com", "District 3, Ho Chi Minh City", "Male", "2001-03-16", NOW(), NOW()),
("TuanAnh","TuanAnh@gmail.com", "District 2, Ho Chi Minh City", "Male", "2000-11-01", NOW(), NOW()),
("VanLinh","VanLinh@gmail.com", "District 1, Ho Chi Minh City", "Female", "1999-08-25", NOW(), NOW()),
("ThiThao","ThiThao@gmail.com", "District 9, Ho Chi Minh City", "Female", "1998-07-04", NOW(), NOW()),
("NgocTrinh","NgocTrinh@gmail.com", "District 8, Ho Chi Minh City", "Female", "1997-05-14", NOW(), NOW()),
("MinhTriet", "MinhTriet@gmail.com", "District 10, Ho Chi Minh City", "Male", "1996-02-28", NOW(), NOW()),
("ThanhTung", "ThanhTung@gmail.com", "District 11, Ho Chi Minh City", "Male", "1995-01-21", NOW(), NOW()),
("ThuHien", "ThuHien@gmail.com", "District 12, Ho Chi Minh City", "Female", "1994-09-03", NOW(), NOW()),
("HongAnh", "HongAnh@gmail.com", "Binh Tan District, Ho Chi Minh City", "Female", "1993-06-15", NOW(), NOW()),
("QuocBao", "QuocBao@gmail.com", "Binh Thanh District, Ho Chi Minh City", "Male", "1992-04-27", NOW(), NOW()),
("ThuyTrang", "ThuyTrang@gmail.com", "Tan Binh District, Ho Chi Minh City", "Female", "1991-03-09", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "Tan Phu District, Ho Chi Minh City", "Male", "1990-01-31", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "Phu Nhuan District, Ho Chi Minh City", "Female", "1989-10-13", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "Go Vap District, Ho Chi Minh City", "Male", "1988-08-24", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "Thu Duc City, Ho Chi Minh City", "Female", "1987-06-06", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "Can Gio District, Ho Chi Minh City", "Male", "1986-04-18", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "Cu Chi District, Ho Chi Minh City", "Female", "1985-02-28", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1984-01-10", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "Nha Be District, Ho Chi Minh City", "Male", "1983-11-22", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "District 13, Ho Chi Minh City", "Female", "1982-10-04", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1981-08-16", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "Cu Chi District, Ho Chi Minh City", "Female", "1980-06-28", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1979-05-10", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "Nha Be District, Ho Chi Minh City", "Female", "1978-03-22", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "District 13, Ho Chi Minh City", "Male", "1977-02-03", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Female", "1976-12-15", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "Cu Chi District, Ho Chi Minh City", "Male", "1975-10-27", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1974-09-08", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "Nha Be District, Ho Chi Minh City", "Female", "1973-07-20", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "District 13, Ho Chi Minh City", "Male", "1972-05-02", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Female", "1971-03-15", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "Cu Chi District, Ho Chi Minh City", "Male", "1970-01-27", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Female", "1969-12-09", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "Nha Be District, Ho Chi Minh City", "Male", "1968-10-21", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "District 13, Ho Chi Minh City", "Female", "1967-09-02", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1966-07-14", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "Cu Chi District, Ho Chi Minh City", "Male", "1965-05-26", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Female", "1964-04-07", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "Nha Be District, Ho Chi Minh City", "Male", "1963-02-19", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "District 13, Ho Chi Minh City", "Female", "1962-01-01", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1961-11-13", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "Cu Chi District, Ho Chi Minh City", "Female", "1960-09-25", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1959-08-07", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "Nha Be District, Ho Chi Minh City", "Female", "1958-06-19", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "District 13, Ho Chi Minh City", "Male", "1957-04-01", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1956-02-13", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "Cu Chi District, Ho Chi Minh City", "Female", "1955-01-25", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1954-12-07", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "Nha Be District, Ho Chi Minh City", "Female", "1953-10-19", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "District 13, Ho Chi Minh City", "Male", "1952-08-31", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Female", "1951-07-13", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "Cu Chi District, Ho Chi Minh City", "Male", "1950-05-25", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Female", "1949-04-06", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "Nha Be District, Ho Chi Minh City", "Male", "1948-02-18", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "District 13, Ho Chi Minh City", "Male", "1947-01-31", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Female", "1946-12-13", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "Cu Chi District, Ho Chi Minh City", "Male", "1945-10-25", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Female", "1944-09-07", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "Nha Be District, Ho Chi Minh City", "Male", "1943-07-20", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "District 13, Ho Chi Minh City", "Female", "1942-05-31", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1941-04-12", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "Cu Chi District, Ho Chi Minh City", "Female", "1940-02-24", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1939-01-05", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "Nha Be District, Ho Chi Minh City", "Male", "1938-11-17", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "District 13, Ho Chi Minh City", "Female", "1937-09-29", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1936-08-11", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "Cu Chi District, Ho Chi Minh City", "Female", "1935-06-23", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1934-05-05", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "Nha Be District, Ho Chi Minh City", "Female", "1933-03-17", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "District 13, Ho Chi Minh City", "Male", "1932-01-29", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Female", "1931-12-11", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "Cu Chi District, Ho Chi Minh City", "Male", "1930-10-23", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1929-09-04", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "Nha Be District, Ho Chi Minh City", "Female", "1928-07-17", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "District 13, Ho Chi Minh City", "Male", "1927-05-29", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Female", "1926-04-10", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "Cu Chi District, Ho Chi Minh City", "Male", "1925-02-21", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Female", "1924-01-03", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "Nha Be District, Ho Chi Minh City", "Male", "1922-11-15", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "District 13, Ho Chi Minh City", "Female", "1921-09-27", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1920-08-09", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "Cu Chi District, Ho Chi Minh City", "Male", "1919-06-21", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Female", "1918-05-03", NOW(), NOW()),
("DinhHung", "DinhHung@gmail.com", "Nha Be District, Ho Chi Minh City", "Male", "1917-03-15", NOW(), NOW()),
("HuyenTrang", "HuyenTrang@gmail.com", "District 13, Ho Chi Minh City", "Female", "1916-01-27", NOW(), NOW()),
("QuangHieu", "QuangHieu@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1914-12-09", NOW(), NOW()),
("KimLan", "KimLan@gmail.com", "Cu Chi District, Ho Chi Minh City", "Female", "1913-10-21", NOW(), NOW()),
("VietPhong", "VietPhong@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1912-09-02", NOW(), NOW()),
("ThiLinh", "ThiLinh@gmail.com", "Nha Be District, Ho Chi Minh City", "Female", "1911-07-14", NOW(), NOW()),
("ThanhTuan", "ThanhTuan@gmail.com", "District 13, Ho Chi Minh City", "Male", "1910-05-26", NOW(), NOW()),
("NguyenDuc", "NguyenDuc@gmail.com", "Binh Chanh District, Ho Chi Minh City", "Male", "1909-04-07", NOW(), NOW()),
("ThiMinh", "ThiMinh@gmail.com", "Cu Chi District, Ho Chi Minh City", "Female", "1908-02-19", NOW(), NOW()),
("VanThanh", "VanThanh@gmail.com", "Hoc Mon District, Ho Chi Minh City", "Male", "1933-03-17", NOW(), NOW());




INSERT INTO payment(pay_method, pay_desc, create_at, update_at) VALUES
("Credit card", "ConCac", NOW(), NOW()),
("Cash", "ConChim", NOW(), NOW()),
("Banking", "ConCu", NOW(), NOW()),
("Debit", "ConCho", NOW(), NOW());



INSERT INTO customer_payment(pay_id, cus_id) VALUES 
(1, 2),
(2, 5),
(3, 5),
(4, 76),
(1, 49),
(2, 28),
(3, 14),
(4, 81),
(1, 66),
(2, 40),
(3, 57),
(4, 34),
(1, 24),
(1, 95),
(1, 72),
(1, 69),
(1, 52),
(1, 86),
(1, 19),
(2, 63),
(2, 83),
(2, 33),
(2, 80),
(2, 47),
(2, 13),
(2, 51),
(2, 82),
(2, 98),
(2, 8),
(3, 55),
(3, 65),
(3, 12),
(3, 74),
(3, 97),
(3, 41),
(3, 43),
(3, 31),
(3, 85),
(3, 90),
(4, 46),
(4, 29),
(4, 93),
(4, 17),
(4, 35),
(4, 11),
(4, 79),
(4, 88),
(4, 67),
(4, 26),
(1, 23),
(1, 70),
(1, 7),
(1, 48),
(1, 30),
(1, 59),
(1, 39),
(1, 44),
(1, 50),
(1, 15),
(1, 100),
(1, 62),
(1, 25),
(1, 68),
(1, 87),
(1, 84),
(1, 18),
(1, 22),
(1, 61),
(1, 16),
(1, 75),
(1, 71),
(1, 96),
(1, 54),
(1, 99),
(1, 9),
(1, 73),
(1, 77),
(1, 38),
(1, 92),
(1, 94),
(1, 42),
(1, 60),
(1, 78),
(1, 6),
(1, 37),
(1, 21),
(1, 58),
(1, 36),
(1, 64),
(1, 45),
(1, 53),
(1, 4),
(1, 56),
(1, 89),
(1, 27),
(1, 91),
(1, 3);




INSERT INTO roles(role_name, role_description, create_at, update_at) VALUES 
("ADMIN", "Add, delete, edit, update", NOW(), NOW()),
("USER", "User has read and create permissions", NOW(), NOW());



INSERT INTO transactions(trans_name, trans_type, pay_id, create_at, update_at) VALUES 
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 2, NOW(), NOW()),
("Buy by cash", "Buy at store", 3, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 1, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 2, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 1, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 4, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 4, NOW(), NOW()),
("Buy by cash", "Buy at store", 3, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 1, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 4, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 4, NOW(), NOW()),
("Buy by cash", "Buy at store", 3, NOW(), NOW()),
("Buy by credit card", "Buy online", 2, NOW(), NOW()),
("Buy by cash", "Buy at store", 3, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 3, NOW(), NOW()),
("Buy by credit card", "Buy online", 4, NOW(), NOW()),
("Buy by cash", "Buy at store", 1, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 3, NOW(), NOW()),
("Buy by credit card", "Buy online", 2, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 1, NOW(), NOW()),
("Buy by cash", "Buy at store", 2, NOW(), NOW()),
("Buy by credit card", "Buy online", 4, NOW(), NOW()),
("Buy by cash", "Buy at store", 1, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 1, NOW(), NOW()),
("Buy by credit card", "Buy online", 2, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 3, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW()),
("Buy by credit card", "Buy online", 2, NOW(), NOW()),
("Buy by cash", "Buy at store", 1, NOW(), NOW()),
("Buy by credit card", "Buy at store", 2, NOW(), NOW()),
("Buy by cash", "Buy online", 1, NOW(), NOW()),
("Buy by credit card", "Buy online", 2, NOW(), NOW()),
("Buy by cash", "Buy at store", 3, NOW(), NOW()),
("Buy by credit card", "Buy online", 2, NOW(), NOW()),
("Buy by cash", "Buy at store", 3, NOW(), NOW()),
("Buy by credit card", "Buy online", 4, NOW(), NOW()),
("Buy by cash", "Buy at store", 4, NOW(), NOW());


INSERT INTO permission(per_module, per_name, create_at, update_at) VALUES 
("INVENTORY;SALES;CUSTOMER;SETTING;MANAGE", "READ;CREATE;UPDATE;DELETE", NOW(), NOW()),
("INVENTORY;SALES;CUSTOMER", "READ;CREATE", NOW(), NOW());


INSERT INTO roles_permissions(role_id, per_id) VALUES 
(1,1),
(2,2);

INSERT INTO accounts(role_id,user_name,hash_pass,create_at,update_at,user_id)
VALUES (1,'trungtran1','$2a$10$frML2j8uTbr46NqJOKFZVOzrdKm9CAm6GzQK/srWBzq.0304ufADi',NOW(),NOW(),2),
    (2,'nhuquynh2110','$2a$10$HCUZjMqMlSOPNPUIG4Oa7OQLuvcAu8ftqYLEVUvt6vSBS8WtP.w/2',NOW(),NOW(),1),
    (2,'anhdung1109','$2a$10$XI8W6ncB2JZCE/pKh7q5g.dmJJZQLFSQtm.VeVZesbzJBjP8c.U8u',NOW(),NOW(),3),
    (2,'tuyetnhi0502','$2a$10$p8ViCmEztwHn886XVfztJOHUHnXL.EMQ0MVO1p0A0FpPdy.fDgHwe',NOW(),NOW(),4),
    (2,'trieuan123','$2a$10$ea8SGMYndleV7fFUiqtzuucGcvoWd9po1dLW8MpPr60S9QzQzzgKy',NOW(),NOW(),5),
    (2,'khanhlinh11','$2a$10$9Kpbur77z.m4ojrczjYwRuABIcO8/f5OnHp8zW6YvZjFDssH5aOei',NOW(),NOW(),6),
    (2,'vietanh1708','$2a$10$/zcKlgXzKcSFUEIW4uC50O9fTxunJ67ibFLBLhyFihag1oZ3Y.o.O',NOW(),NOW(),7),
    (2,'ducminh1403','$2a$10$rjy2cmzWaSU2nxDtPZzqjesmMUuOlZBqCF0TupQsmiWNyX8bsL/p.',NOW(),NOW(),8),
    (2,'thutrang296','$2a$10$JTTXCo4RH50hK2yi1mg0Memsm8F7Q5hIa3WnRYQ60Cnc6AzKn2Ml2',NOW(),NOW(),9),
    (2,'hanhphuc0309','$2a$10$ApLWF2TBHqzmIyXxROMLAuEE49EPbCQw6QB2l/0cu5woAn6nompUC',NOW(),NOW(),10),
    (2,'huyhoang1212','$2a$10$jgrsbSmlXkYfWjbLAxBBmO2VWyAJ5kHiUui4CybTRiavdQ3JE0fYC',NOW(),NOW(),11),
    (2,'namson2604','$2a$10$hxZoQi7GrZdjknXyI6gDAO7O/DVr/8st916rBW0/uB5RQokvGsi36',NOW(),NOW(),12),
    (2,'ngocmai0911','$2a$10$ktir.UcDx6bMqXKUhFpGze5EedSuy4V2cVYe7LYKnp3s1h.jpJSrm',NOW(),NOW(),13),
    (2,'thanhcong1402','$2a$10$nDioyrUSGrcQhB6duwuf3eXFXp6DsdiH3hUZjBxn9raOwxtvAuMuG',NOW(),NOW(),14),
    (2,'maihoa3107','$2a$10$KZlTRfV.XW8NamSeN22rNu7ZjlpXvQnr0JCOtCgHIaEpJJqmSlPse',NOW(),NOW(),15),
    (2,'dinhquan1810','$2a$10$0qZctmyP1pthD1oHe0D5N.YvSHeIXJe4083H9YYiwSaAS7X91TK7u',NOW(),NOW(),16),
    (2,'thuytrang2503','$2a$10$2f2QtVB3sAmiOwCn/tSqBeN8sgop89K2xNEAIm.xBVP5NjQ0kmaG2',NOW(),NOW(),17),
    (2,'tienquan0106','$2a$10$WUAaTNVIFcWlhgpaVuBpbeOt4SUDD0s0tneLLRoENh76FiYIFqYVG',NOW(),NOW(),18),
    (2,'vanduc1509','$2a$10$ebOkrN3b4cyNW9xpNKvSQuskppLn7pROpBlb/AES7/L.s.T6JfALi',NOW(),NOW(),19),
    (2,'hoangyen2312','$2a$10$bhRebfoeb.VugwqgzywNP.Ivt2tCHdl.RRXdV7CMlKHJGWFba7uTC',NOW(),NOW(),20),
    (2,'quanminh0805','$2a$10$k6UehQSlTV8AO4wTq63hy.rYBRMZ0JsKtje8k4R2.0Gjb5W2oUXDm',NOW(),NOW(), 21),
    (2,'thanhdat2008','$2a$10$fZvttz5n./kDKrWtlQY6UOvdraRCpsfOQKQcNMCJuW5oINwAco9iu', NOW(),NOW(),22);